### PR TITLE
Added qemu to the imx8 cross-compile build

### PR DESCRIPTION
**Pull request by jkuro-tii**
Added qemu (dynamically linked) to the image.

### CODE REVIEW

**Comment by jkuro-tii** [comment]
Added qemu to the imx8 cross-compile build. qemu is built against shared libraries; it's not designated for a release build, but rather for porting already existing solutions based on qemu, implemented on other Linux distros. Requires nixpkgs-spectrum coming from the same branch name.

**Review by vilvo — COMMENTED** [review]
Could not compile it without or with garbage collection of nix store. I tested by cherry-picking your patch on top of `tiiuae:aarch64-imx8-crosscompile` as your branch does not have `qxp`-image build patch(es).
Error I get is:
```
error (ignored): error: cannot unlink '/tmp/nix-build-unbound-aarch64-unknown-linux-musl-1.14.0.drv-0/unbound-1.14.0': Directory not empty
error: derivation '/nix/store/2qfxyn0d34baqc2r6xc4sx68flxxmh4y-fonts.conf.drv' requires non-existent output 'out' from input derivation '/nix/store/p06f6kcbvpvivh23x3j0rb8jxn73aspd-fontconfig-aarch64-unknown-linux-musl-2.13.94.drv'
```
Need to analyze it further.

**Comment by vilvo** [comment]
> ... Requires nixpkgs-spectrum coming from the same branch name.

Do you mean this one https://github.com/tiiuae/nixpkgs-spectrum/pull/4 ?

**Comment by jkuro-tii** [comment]
> Could not compile it without or with garbage collection of nix store.

I'm facing the same when using the http://binarycache.vedenemo.dev cache server. When it's turned off, build process is proper.

https://securesystem-71s3304.slack.com/archives/C033GSEA3PV/p1662625631812159

> Do you mean this one https://github.com/tiiuae/nixpkgs-spectrum/pull/4 ?
Yes.

**Comment by jkuro-tii** [comment]
> as your branch does not have qxp-image build patch(es).

I pushed  the aarch64-imx8-crosscompile branch rebased on the top of https://github.com/tiiuae/spectrum, so on my fork it contains all the updates. From my site it still contains only the qemu change.

**Pull request closed without merging**
