### PR TITLE
Create an image for i.MX 8QuadMax MEK

### PR DESCRIPTION
**Pull request by panufi**
Signed-off-by: Panu Finnila <panu.finnila@unikie.com>

### CODE REVIEW

**Review by vilvo — APPROVED** [review]

**Comment by jkuro-tii** [comment]
Does the update require changes in Nix packages? While building I get the following error:

error: attribute 'ubootIMX8QM' missing
       at /home/jk/cross-compile/qemu/test/spectrum-1/img/imx8qm/default.nix:10:11:
            9| let
           10|   uboot = pkgs.ubootIMX8QM;
             |           ^
           11|   spectrum = import ../live { inherit pkgs; };
(use '--show-trace' to show detailed location information)

**Comment by panufi** [comment]
> Does the update require changes in Nix packages? While building I get the following error:
> 
> error: attribute 'ubootIMX8QM' missing at /home/jk/cross-compile/qemu/test/spectrum-1/img/imx8qm/default.nix:10:11: 9| let 10| uboot = pkgs.ubootIMX8QM; | ^ 11| spectrum = import ../live { inherit pkgs; }; (use '--show-trace' to show detailed location information)

Yes, it needs aarch64-imx8qm-uefi-boot branch at nixpkgs

**Comment by vilvo** [comment]
Tested this but it does not build for me:
```
❯ git --git-dir=spectrum/.git branch
* (HEAD detached at origin/aarch64-imx8qm-image)
❯ git --git-dir=nixpkgs-spectrum/.git branch
* (HEAD detached at origin/aarch64-imx8-crosscompile)
❯ NIXPKGS_ALLOW_UNFREE=1 nix-build spectrum/img/imx8qm/ -I nixpkgs=nixpkgs-spectrum
error: attribute 'ubootIMX8QM' missing

       at /home/vilvo/prs/spectrum/img/imx8qm/default.nix:10:11:

            9| let
           10|   uboot = pkgs.ubootIMX8QM;
             |           ^
           11|   spectrum = import ../live { inherit pkgs; };
(use '--show-trace' to show detailed location information)
```

**Comment by vilvo** [comment]
>``` 
> error: attribute 'ubootIMX8QM' missing
> 
>        at /home/vilvo/prs/spectrum/img/imx8qm/default.nix:10:11:
> 
>             9| let
>            10|   uboot = pkgs.ubootIMX8QM;
>              |           ^
>            11|   spectrum = import ../live { inherit pkgs; };
> (use '--show-trace' to show detailed location information)
> ```

@panufi so if we want to build uboot for IMX8QM, we need to add target for it - like https://github.com/tiiuae/nixpkgs-spectrum/commit/b29e4534119f88f9532e5246d45c09e2d17e0ff4 - otherwise we would need to use QXP uboot instead to build the image.

**Review by vilvo — CHANGES_REQUESTED** [review]
Not merging this as such even when it does not break the build for QXP. It's missing the referred target for QM uboot.

**Comment by vilvo** [comment]
> Yes, it needs aarch64-imx8qm-uefi-boot branch at nixpkgs

Sure, builds. Please create a PR to merge that to `aarch64-imx8-crosscompile` branch in `nixpkgs-spectrum`. Let's merge that first and then this.

**Review by vilvo — APPROVED** [review]
Can be merged with https://github.com/tiiuae/nixpkgs-spectrum/commit/9804c4a96b3d46049f7998d74dd786ee51df3260

**Pull request merged**
